Use "delphix-rust" instead of Ubuntu's Rust packages
delphix/linux-pkg pull request #190
Opened 2021-09-09 20:55 UTC by prakashsurya

2021-09-09 20:58 UTC, prakashsurya commented
`build-package` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/zfs/job/pre-push/199/)

2021-09-09 21:00 UTC, pzakha approved these changes

2021-09-09 21:04 UTC, pzakha requested changes
Hmm I think I approved this too quickly. You'll need to add a linux-pkg package dependency in zfs/config.sh:
```
PACKAGE_DEPENDENCIES="delphix-rust" 
```
And then install the debs from `"$DEPDIR"/delphix-rust/`. You can check for other packages like bpftrace or grub2 for how it's done.

2021-09-09 21:09 UTC, prakashsurya commented
ah, right.. done.. updated the testing link too.

2021-09-09 21:10 UTC, pzakha commented
Looks like the checks are failing because we are making some assumptions about the zfs package's dependencies, so might need to update the checks.

2021-09-09 21:14 UTC, pzakha approved these changes

2021-09-09 21:14 UTC, pzakha commented on packages/zfs/config.sh
> +		delphix-rust \
I think you'll need to remove this line too.

2021-09-10 00:51 UTC, ahrens approved these changes

2021-09-10 15:51 UTC, merged