GHM-822 Build virtalization package with secrets
delphix/linux-pkg pull request #260
Opened 2022-10-20 20:17 UTC by matt-skinner-delphix

Corrections from previous PR include fixing the quoting around the arguments.

Also did more manual testing to confirm that linux-pkg invocation of the new targets with correct parameters passed in build the app-gate correctly.

See http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3606/ (already passed the linux-pkg phase).

2022-10-20 20:27 UTC, prakashsurya commented on packages/virtualization/config.sh
> +	echo "---- ${args[@]}"
do we really want to be dumping sensitive information to stdout?

2022-10-20 20:27 UTC, prakashsurya approved these changes

2022-10-21 21:23 UTC, grodr approved these changes

2022-10-24 15:55 UTC, sebroy requested changes

2022-10-24 15:55 UTC, sebroy commented on packages/virtualization/config.sh
> +	# Because ant does not read the environment variables of the execution context, we set them as
I'm a bit skeptical of this comment on its face. Ant can read environment variables in general (e.g. https://coderanch.com/t/108737/build-tools/read-environment-variables-Ant). Is there something specific about our use of ant that prohibits this?

2022-10-24 15:55 UTC, sebroy commented on packages/virtualization/config.sh
> +	logmust ant "${args[@]}" all-secrets package
Does this mean that we will log the private key and other args set above in the jenkins console log? I'm still not completely convinced that our ant build.xml couldn't read these from the environment using the `environment` property...

2022-10-24 16:25 UTC, matt-skinner-delphix commented on packages/virtualization/config.sh
> +	logmust ant "${args[@]}" all-secrets package
You can confirm this by checking the build at http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3606/ Jenkins redacts the secret.

2022-10-24 16:43 UTC, matt-skinner-delphix commented on packages/virtualization/config.sh
> +	# Because ant does not read the environment variables of the execution context, we set them as
Comment removed. The value gained by redesigning to use environment variables is not worth delaying other work. Because this is an public discussion I am stopping here. If you wish to discuss further we can do it more openly in private.

2022-10-24 16:51 UTC, sebroy approved these changes

2022-10-24 20:13 UTC, merged