TOOL-16737 Update "add_swap" function to work on Delphix buildserver
delphix/linux-pkg pull request #264
Opened 2022-11-14 22:30 UTC by prakashsurya

2022-11-14 22:31 UTC, prakashsurya commented
- `git-ab-pre-push -b bcc` is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3779/)

2022-11-14 23:08 UTC, sebroy requested changes

2022-11-14 23:08 UTC, sebroy commented on setup.sh
> +		logmust sudo chmod 600 "$swapfile"
I'm not sure these commands make sense in the case where you're using a swap device. The device partition is a block device, so I'm not sure what fallocate will do in that case (fail, I'm guessing?). Also, you'd be changing the permissions on the `/dev` node, which is probably not what you want to do.

I think you can omit both of those commands, and the `mkswap` command will use the whole disk partition you point it at.

2022-11-14 23:32 UTC, prakashsurya commented on setup.sh
> +		logmust sudo chmod 600 "$swapfile"
right.. but this block is only executed when the root filesystem is _not_ zfs.. i.e. when using the ubuntu buildserver..

so I agree.. I think you might have read the logic incorrectly though.. I'm specifically avoiding these calls when using the block device directly..

at least, that's the intention.. let me know if I got it wrong..

2022-11-15 00:59 UTC, sebroy commented on setup.sh
> +		logmust sudo chmod 600 "$swapfile"
You're right, I read this wrong. It's possible that I glanced at an earlier version of the PR that had the code organized slightly differently, but regardless, this looks right now.

2022-11-15 00:59 UTC, sebroy approved these changes

2022-11-15 03:19 UTC, don-brady approved these changes

2022-11-15 03:19 UTC, merged