RENG-145 Update config.sh fetch and pass upstream branch to the linux-pkg ant task
delphix/linux-pkg pull request #296
Opened 2023-07-03 11:56 UTC by shishaktdlpx

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2023-07-04 04:56 UTC, km4dlpx commented on packages/virtualization/config.sh
> +	if [[ ${UPSTREAM_PRODUCT_BRANCH+nothing} ]]; then
@shishaktdlpx How does this variable get the upstream branch value?

2023-07-04 05:09 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	if [[ ${UPSTREAM_PRODUCT_BRANCH+nothing} ]]; then
In the `linux_pkg_build_package.groovy` the **$UPSTREAM_PRODUCT_BRANCH** is already defined in their `env` so it will take it from there. 
An example of that can be found here. http://selfservice.jenkins-shishaktkumar.dcol2.delphix.com/job/linux-pkg/job/develop/job/build-package/job/virtualization/job/pre-push/1/console 
`17:16:43  Running: ant -Dbuild.branch=develop -DSECRET_DB_USE_JUMPBOX=true`

2023-07-17 15:03 UTC, jorge-delphix approved these changes

2023-07-17 16:13 UTC, palash-delphix requested changes

2023-07-17 16:13 UTC, palash-delphix commented on packages/virtualization/config.sh
> +	if [[ ${UPSTREAM_PRODUCT_BRANCH+nothing} ]]; then
Shouldn't this be `DEFAULT_GIT_BRANCH`?

2023-07-17 16:13 UTC, palash-delphix commented on packages/virtualization/config.sh
> +	fi
Shouldn't this raise an exception if the branch is not set?

2023-07-18 01:55 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	fi
The code to raise exception is already there in the pipeline.

2023-07-18 01:55 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	if [[ ${UPSTREAM_PRODUCT_BRANCH+nothing} ]]; then
Updated.

2023-07-18 01:57 UTC, palash-delphix commented on packages/virtualization/config.sh
> +	fi
This code can also be run outside of the pipeline and should have it's own `check_env`. See other instances of `check_env` in this repo.

2023-07-18 02:19 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	fi
https://github.com/delphix/linux-pkg/blob/203e5932d03f53e3ecadbaa5fb8b58d96c545b34/buildpkg.sh#L70

the code for check_env is already in `buildpkg.sh` before triggering the build function. I don't think we should write extra `check_env` inside `config.sh` .

2023-07-18 04:32 UTC, palash-delphix commented on packages/virtualization/config.sh
> +	fi
@shishaktdlpx So if this variable is always set, we can remove the `if` statement, right?

2023-07-18 08:59 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	fi
Yes I think so. But there is no harm to let it be.

2023-07-18 14:41 UTC, palash-delphix commented on packages/virtualization/config.sh
> +	fi
If there is a caller of this function that does not set the env var, the function will not fail early. I think we should remove it.

2023-07-18 15:05 UTC, shishaktdlpx commented on packages/virtualization/config.sh
> +	fi
Done.

2023-07-18 15:09 UTC, palash-delphix approved these changes
Please retest your final diff

2023-07-19 11:09 UTC, merged