Modify kernel build to include Delphix's custom annotations
delphix/linux-pkg pull request #300
Opened 2023-09-08 16:02 UTC by palash-delphix

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2023-09-08 18:06 UTC, prakashsurya reviewed
I'm not necessarily convinced this is needed.. have we gotten multiple merge conflicts already? or only one?

With that said, I'm also not opposed to this change, from a design perspective...

If we want to go with this approach, I think I'd recommend we also look into dynamically creating the `debian.delphix/config/annotations` file too.. what do you think?

2023-09-08 18:44 UTC, palash-delphix commented
> I'm not necessarily convinced this is needed.. have we gotten multiple merge conflicts already? or only one?

We have only gotten 1 merge conflict so far. We can wait and observe if this change is really needed.

> With that said, I'm also not opposed to this change, from a design perspective...
> 
> If we want to go with this approach, I think I'd recommend we also look into dynamically creating the `debian.delphix/config/annotations` file too.. what do you think?

That's also an option, yes. We could move the annotations file to `linux-pkg` or have logic that creates the file right before building it. But I figured it's easier for the configuration to live in the repo itself.  Generating the config has the same pros & cons as the 2 options listed here. Or did you have something else in mind?

2023-09-08 18:59 UTC, prakashsurya commented
I think I actually like option 2, over what you have here.. and then, merging that with what I mentioned in my comment.. we could change `-f debian.delphix/config/annotations` to point to a single file that lives in this repository (linux-pkg), and is used for all of our kernel repositories..

Obviously, that means the config we use to override must apply to all the different platforms, but I think the file is the same today, so that would work. If we find that doesn't work in the future, we can think about how to extend it to work for platform specific overrides.

2023-09-11 21:53 UTC, prakashsurya approved these changes

2023-09-15 14:38 UTC, sebroy requested changes

2023-09-15 14:38 UTC, sebroy commented on resources/delphix_kernel_annotations
> +# FLAVOUR: amd64-aws
Is this FLAVOUR thing used for anything? Since we're using this single annotations file for all of our "flavours", this doesn't seem correct.

2023-09-15 14:38 UTC, sebroy commented on default-package-config.sh
>  	#
Can you expand this comment a bit to explain the annotations design? We have this Delphix-specific annotations file, but it would be good to explain what the annotations command does, and how it is that calling it twice does the right thing (and the idea that the ordering of the calls might matter?).

2023-09-15 18:00 UTC, palash-delphix commented on default-package-config.sh
>  	#
Done

2023-09-15 18:01 UTC, palash-delphix commented on resources/delphix_kernel_annotations
> +# FLAVOUR: amd64-aws
Good catch, while it doesn't really matter, I think we should follow the recommended format. I added all flavours to this line.

2023-09-19 15:02 UTC, sebroy approved these changes

2023-09-19 15:03 UTC, merged